# docker-compose.yml
version: '3'

services:
  postgres:
    image: postgres:14
    container_name: postgres_crud
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: code_drops_crudcruddb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
